deployments:
- name: nyc_taxi_yellow_2022
  entrypoint: orchestrate.py:main_flow
  work_pool: 
    name: mlops-zoompool
- name: nyc_taxi_yellow_2022_gcp
  entrypoint: orchestrate_gcp.py:main_flow_gcp
  work_pool: 
    name: mlops-zoompool
- name: nyc_taxi_green_2021
  entrypoint: orchestrate_3_4.py:main_flow_3_4
  work_pool: 
    name: mlops-zoompool
- name: nyc_taxi_green_j_f_23
  entrypoint: orchestrate_j_f_23.py:main_flow_j_f_23
  work_pool: 
    name: mlops-zoompool
- name: nyc_taxi_green_f_m_23
  entrypoint: orchestrate_f_m_23.py:main_flow_f_m_23
  work_pool: 
    name: mlops-zoompool

