deployments:
- name: nyc_taxi_yellow_2022
  entrypoint: orchestrate.py:main_flow
  work_pool: 
    name: mlops-zoompool
- name: nyc_taxi_yellow_2002_gcp
  entrypoint: orchestrate_gcp.py:main_flow_gcp
  work_pool: 
    name: mlops-zoompool
