deployments:
- name: nyc_taxi_yellow_2022
  entrypoint: orchestrate.py:main_flow
  work_pool: 
    name: mlops-zoompool
- name: taxi_gcp_data
  entrypoint: orchestrate_gcp.py:main_flow_gcp
  work_pool: 
    name: mlops-zoompool
