deployments:
- name: taxi_local_data
  entrypoint: orchestrate.py:main_flow
  work_pool: 
    name: mlops-zoompool
- name: taxi_gcp_data
  entrypoint: orchestrate_gcp.py:main_flow_gcp
  work_pool: 
    name: zoompool
